import type { Metadata } from "next"
import SideBar from "../_layouts/sidebar"
import Header from "../_layouts/header"
import { CopyRight } from "../_layouts/copyright"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

interface LayoutProps {
    children: React.ReactNode
    params: string
}

export default function RootLayout({ children, params }: LayoutProps) {
    return (
        <div className="h-screen w-screen flex ">
            <SideBar />
            <div className="flex flex-col w-full">
                <Header />
                {children}
                <CopyRight />
            </div>
        </div>
    )
}
