import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'dashboard2',
  description: 'Generated by create next app',
};
const DashboardLayouts = ({ children }: { children: React.ReactNode }) => {
  return <>{children}</>;
};

export default DashboardLayouts;
