import { Metadata } from "next"
import { KGADevel } from "./_components/(icon)/Logo"

export const metadata: Metadata = {
    title: "404-Not Found",
    description: "Generated by create next app",
}
const ErrorPage = () => {
    return (
        <div className="flex flex-col w-full h-screen justify-center items-center bg-black">
            <div className="w-[300px] h-[300px] text-gray-300 rounded-[30px] p-10 text-center font-bold text-lg">
                <h1 className="ml-[-100px]">
                    <KGADevel />
                </h1>
                현재 페이지가 존재하지 않거나 공사중 입니다.
            </div>
        </div>
    )
}

export default ErrorPage
